export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILED = 'USER_FAILED';

export const TODOS_REQUEST = 'TODOS_REQUEST';
export const TODOS_SUCCESS = 'TODOS_SUCCESS';
export const TODOS_FAILED = 'TODOS_FAILED';
export const TODOS_DELETE = 'TODOS_DELETE';
export const SET_TODO_COMPLETE = 'SET_TODO_COMPLETE';
export const CREATE_TODO = 'CREATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';